add previous and next relations
alanorth/hugo-theme-bootstrap4-blog pull request #55
Opened 2017-03-19 01:06 UTC by xenoterracide

GH #51 

https://www.w3.org/TR/html5/links.html#link-type-next

2017-03-19 15:53 UTC, alanorth requested changes
Good addition, but need two minor changes.

2017-03-19 15:53 UTC, alanorth commented on layouts/_default/list.html
> +  <a class="btn btn-outline-primary disabled" href="#" role="button" rel="next" aria-disabled="true">{{ i18n "paginatorNext" }}</a>
Perhaps doesn't need to be here since the button is disabled in this case (no next page).

2017-03-19 15:53 UTC, alanorth commented on layouts/_default/list.html
> +  <a class="btn btn-outline-primary disabled" href="#" role="button" rel="prev" aria-disabled="true">{{ i18n "paginatorPrevious" }}</a>
Perhaps doesn't need to be here since the button is disabled in this case (no previous pages).

2017-03-20 21:56 UTC, alanorth commented
Psst, @xenoterracide. Two small changes to get this merged.

2017-03-21 01:05 UTC, xenoterracide commented
done,  I can squash if necessary though I don't think I can do that on GH

2017-03-24 08:59 UTC, alanorth commented
Looks good to me, @xenoterracide. Don't worry about squashing, I'm not Linus Torvalds so my standards for commits are slightly lower—at least you didn't add a bunch of unnecessary whitespace! 😝

2017-03-24 08:59 UTC, merged

2017-03-24 09:01 UTC, alanorth commented
Oh, looks like I squashed it into one commit on the GitHub interface. Pretty slick!